export default [{
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '1',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '刻录机啊',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_USER_COMPANY',
    id: '2',
    source: 12,
    status: 'DATA_NORMAL',
    tagname: '大是大非',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_USER_COMPANY',
    id: '3',
    source: 12,
    status: 'DATA_NORMAL',
    tagname: '如何饿饿',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '4',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '5',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视1',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '6',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视2',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '7',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视7',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '8',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视8',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '9',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视9',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '10',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视10',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '11',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视11',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '12',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视12',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '13',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视13',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '14',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视14',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '15',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视15',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '16',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视16',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '17',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视17',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '18',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视18',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '19',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视19',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '20',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视20',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '21',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视21',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '22',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视22',
    tagsource: 22,
  },
  {
    etagtype: 'EVALUATION_COMPANY_USER',
    id: '23',
    source: 12,
    status: 'DATA_DISABLED',
    tagname: '更好看电视23',
    tagsource: 22,
  }
];
